Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
Resources:
Ec2Instance:
  Type: "AWS::EC2::Instance"
  Properties:
    InstanceType:
      Ref: InstanceTypeParameter
    ImageId: "ami-0306ea53026b71499"
